### ISSUE TITLE
Package not getting installed

### ISSUE THREAD

**Issue by niruvt** [dedalozzo/pygmentize#4]
I am trying to install this package.
I am getting these errors.
```
ERROR: Could not find a version that satisfies the requirement pygmentize==2.0 (from versions: none)
ERROR: No matching distribution found for pygmentize
```

I've looked [this](https://github.com/lambdamusic/Ontospy/issues/70) issue, but the problem there was absence of `pygments`.

If I issue the suggested command, I'm getting this result -
```
Requirement already satisfied: pygments in ./.local/lib/python3.6/site-packages (2.4.2)
```
I've also PHP installed. (version 7.2.19)

Having these dependencies installed also is not resulting in the successful installation.

**Comment by dedalozzo** [comment]
Hi @NiranjanTambe, can you run `pygmentize` from the shell? If you get an error means it's not in your env path. You can modify your env path following this [answer](https://superuser.com/questions/488173/how-can-i-edit-the-path-on-linux).

**Comment by niruvt** [comment]
But what should be the appropriate destination for the path then?

**Comment by niruvt** [comment]
> can you run `pygmentize` from the shell?

Can you please explain how to do this? I am sorry to ask these super basic question, but I am learning to use terminal.

**Comment by dedalozzo** [comment]
You should find where is the file, and add the directory to your PATH, or create a symlink in a directory already in your PATH, for example `/usr/bin` or `/bin`. To locate the file you can use `updatedb` in the root directory, then `locate pygmentize`.

**Comment by dedalozzo** [comment]
> > can you run `pygmentize` from the shell?
> 
> Can you please explain how to do this? I am sorry to ask these super basic question, but I am learning to use terminal.

Just open a terminal and type `pygmentize`. You should get an error I assume.

**Comment by niruvt** [comment]
> Just open a terminal and type `pygmentize`

Something happened to my terminal, it isn't showing any error, but also not showing the regular user name and $

**Comment by dedalozzo** [comment]
Please press CTRL+C to return to the prompt.

**Comment by niruvt** [comment]
```
^CTraceback (most recent call last):
  File "/home/ubuntu/.local/bin/pygmentize", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pygments/cmdline.py", line 548, in main
    return main_inner(popts, args, usage)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pygments/cmdline.py", line 402, in main_inner
    code = sys.stdin.buffer.read()
KeyboardInterrupt
```

**Comment by dedalozzo** [comment]
It seems you can run it, so PHP should run it as well. Try to type `pygmentize -L` please, and paste the output here.

**Comment by niruvt** [comment]
https://pastebin.com/8WTkkEBS

**Comment by dedalozzo** [comment]
As far as I can see you have pygments installed, and apparently it works. You should be fine.

**Comment by niruvt** [comment]
Ok. Let me read about the environment and path and if any doubt I'll ask again. Thanks for your immediate response :+1:

**Comment by dedalozzo** [comment]
Let me know if you have any trouble. I think you do not need to update your path. I think you can follow the instructions, modify your `composer.json` like per instructions in the README.me.

**Comment by niruvt** [comment]
I read the instructions. 
```
{
    "require": {
        "3f/pygmentize": "dev-master"
    },
}
```
This was giving an red colored error-box.

![error](https://user-images.githubusercontent.com/54938729/65261965-fd836e00-db26-11e9-90d6-e1d1bb803787.png)

I just tried to interpret it and removed the comma and the process was completed. I was able to perform my desired tasks. Just a request, if that comma is really unnecessary, please remove it from the instructions also. Somebody new might stumble at the installation itself.

**Comment by dedalozzo** [comment]
> Just a request, if that comma is really unnecessary, please remove it from the instructions also. Somebody new might stumble at the installation itself.

I will, thank you for reporting this.
